# Generated by Django 2.1 on 2018-08-22 14:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import robot_factory.robots.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('configuration', django.contrib.postgres.fields.jsonb.JSONField(default=robot_factory.robots.models._default_configuration_fields)),
                ('qa_status', models.CharField(choices=[('factory_seconds', 'Factory Seconds'), ('passed_qa', 'Passed QA')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('robots', models.ManyToManyField(to='robots.Robot')),
            ],
        ),
    ]
