# Generated by Django 2.1 on 2018-08-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='robots',
            field=models.ManyToManyField(related_name='status', to='robots.Robot'),
        ),
    ]
